apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: samuelmaiyo/reverseproxy:v7
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USERNAME
            value: Maiyo
          - name: POSTGRES_PASSWORD
            value: maiyoudagram
          - name: POSTGRES_HOST
            value: maiyoudagram.c1cvlaujd6hj.us-east-1.rds.amazonaws.com
          - name: AWS_BUCKET
            value: arn:aws:s3:::udagram-maiyo-bucket
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_PROFILE
            value: udacity
          - name: JWT_SECRET
            value: testing
          - name: URL
            value: http://localhost:8100
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m