# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=Maiyo
export POSTGRES_PASSWORD=maiyoudagram
export POSTGRES_HOST=maiyoudagram.c1cvlaujd6hj.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=arn:aws:s3:::udagram-maiyo-bucket
export AWS_REGION=us-east-1
export AWS_PROFILE=project3
export JWT_SECRET=testing
export URL=http://localhost:8100
export AWS_ACCESS_KEY_ID=ASIAY46WVKEDFDRMFKPZ
export AWS_SECRET_ACCESS_KEY=S9fLwc9EvUghXmMrRXsIP0bU7ghYEkwgdDZRDU2x
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEEYaDBmI2rlDlVNPbHqBECLVARVyXwVcHOAYN6QTX9xbpNjCia/gT3FgUhyCWIcFZC8OU6qzPmDrAbouf8ZLERV9phyJDuIYgd18ULGH4xX86OPTU2+3lljYlzwOznVquekljYILY8oxlzpkaxbWuZGtQfm1qSOcw0VYSKOISsT4BGnx6exiyIWcQVV1TpiNDZbcPSQlndwkNRUn6WBmQGQGJwKIqkEAPRcqn8VIG5cZ8Q/NYHghjPSJOiOt0O4FYxBWh+0erRQV+fu/Nfoi3n+xU1Y9BuyAM6r6DLSgM9pakw9nO33hASju/sKZBjItW8nc0eZIsjdTFa3La5AFP3x4c0aGugDi0BEc4PDyrEcdmeoNavSzlBbeXFvY