# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=Maiyo
export POSTGRES_PASSWORD=maiyoudagram
export POSTGRES_HOST=maiyoudagram.c1cvlaujd6hj.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=arn:aws:s3:::udagram-maiyo-bucket
export AWS_REGION=us-east-1
export AWS_PROFILE=udacity2
export JWT_SECRET=testing
export URL=http://localhost:8100
export AWS_ACCESS_KEY_ID=ASIAY46WVKEDK5P7LC65
export AWS_SECRET_ACCESS_KEY=TbJ5KHi2RRUIMe0C37udEBwWTflLrTTgOINYU3hY
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEDoaDD5bmSLexTWHyc6CAyLVAQYljKyOLtJebSQexHuSG9IOYl1klDTVM6NhrWmjferGQZE1LBLe/qJJr+AoprSRLqyaB5L3RpjpXvThv1Bl9OA4+w6IMQnB8J7hCkddw1xuziXKzeF9p27WCS2J8gwdfuV4q201tOEnWCKjT3NKslKhEpmA9SgmwO0MeoLv3AtySoKKqnVvcsAPC98xh4LFzdZZ2LVJuz9J3dBRfuy35eht99OXLJ+FCAqoRfvSP1bbJasqydDJ+CNg0Jev596IXFCwNF/02m0F45lDf/XvtOODlZLO+SjlqMCZBjItk+btiEkFZgue+pyimjIO32HkeJixnyDUBHfkWu8dehNMDCl8LVrVnqrAzUDA